"""empty message

Revision ID: 092985c720c5
Revises: 8c992a21df27
Create Date: 2023-07-04 08:30:21.762245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '092985c720c5'
down_revision = '8c992a21df27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marathon_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vk_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['marathon_groups.id'], name=op.f('fk_marathon_users_group_id_marathon_groups')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_marathon_users'))
    )
    with op.batch_alter_table('marathon_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_marathon_users_vk_id'), ['vk_id'], unique=True)

    op.create_table('status_of_marathon_users_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_number', sa.Integer(), nullable=True),
    sa.Column('task_status', sa.String(length=16), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['marathon_groups.id'], name=op.f('fk_status_of_marathon_users_tasks_group_id_marathon_groups')),
    sa.ForeignKeyConstraint(['user_id'], ['marathon_users.id'], name=op.f('fk_status_of_marathon_users_tasks_user_id_marathon_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_status_of_marathon_users_tasks'))
    )
    with op.batch_alter_table('status_of_marathon_users_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_status_of_marathon_users_tasks_task_number'), ['task_number'], unique=False)

    op.drop_table('users_participating_in_the_marathon')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_participating_in_the_marathon',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('group_id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['marathon_groups.id'], name='fk_users_participating_in_the_marathon_group_id_marathon_groups'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_users_participating_in_the_marathon_user_id_user'),
    sa.PrimaryKeyConstraint('id', name='pk_users_participating_in_the_marathon')
    )
    with op.batch_alter_table('status_of_marathon_users_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_status_of_marathon_users_tasks_task_number'))

    op.drop_table('status_of_marathon_users_tasks')
    with op.batch_alter_table('marathon_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_marathon_users_vk_id'))

    op.drop_table('marathon_users')
    # ### end Alembic commands ###
