"""empty message

Revision ID: 116b0b9852a0
Revises: fae8a34e5a14
Create Date: 2023-05-29 07:07:54.369372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '116b0b9852a0'
down_revision = 'fae8a34e5a14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('number_of_tasks_in_the_marathon_table', schema=None) as batch_op:
        batch_op.drop_constraint('fk_number_of_tasks_in_the_marathon_table_table_id_google_marathon_tables', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_number_of_tasks_in_the_marathon_table_table_id_table_column_settings'), 'table_column_settings', ['table_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('number_of_tasks_in_the_marathon_table', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_number_of_tasks_in_the_marathon_table_table_id_table_column_settings'), type_='foreignkey')
        batch_op.create_foreign_key('fk_number_of_tasks_in_the_marathon_table_table_id_google_marathon_tables', 'google_marathon_tables', ['table_id'], ['id'])

    # ### end Alembic commands ###
