"""empty message

Revision ID: 216a322b23c4
Revises: e128f44b30a7
Create Date: 2023-07-14 03:28:30.022381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '216a322b23c4'
down_revision = 'e128f44b30a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apscheduler_jobs', schema=None) as batch_op:
        batch_op.drop_column('jobs_name')
        batch_op.drop_column('next_run_time')
        batch_op.drop_column('job_state')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apscheduler_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_state', sa.VARCHAR(length=128), nullable=True))
        batch_op.add_column(sa.Column('next_run_time', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('jobs_name', sa.VARCHAR(length=128), nullable=True))

    # ### end Alembic commands ###
