"""empty message

Revision ID: 268ba756a89a
Revises: 18b21859a4fd
Create Date: 2023-07-08 14:52:36.729444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '268ba756a89a'
down_revision = '18b21859a4fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_with_access_to_the_panel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vk_id', sa.Integer(), nullable=True),
    sa.Column('access', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users_with_access_to_the_panel'))
    )
    with op.batch_alter_table('users_with_access_to_the_panel', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_with_access_to_the_panel_vk_id'), ['vk_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_with_access_to_the_panel', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_with_access_to_the_panel_vk_id'))

    op.drop_table('users_with_access_to_the_panel')
    # ### end Alembic commands ###
