"""empty message

Revision ID: 3741118028e3
Revises: f57b08ce6ffa
Create Date: 2023-05-28 05:10:49.968226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3741118028e3'
down_revision = 'f57b08ce6ffa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('access_rights_for_curators_in_groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_access_rights_for_curators_in_groups_user_id_user'), 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('access_rights_for_curators_in_groups', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_access_rights_for_curators_in_groups_user_id_user'), type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
