"""empty message

Revision ID: 3ad8f6b6c4ee
Revises: 8d399b7c4423
Create Date: 2023-05-28 07:21:03.369347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ad8f6b6c4ee'
down_revision = '8d399b7c4423'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('google_marathon_tables', schema=None) as batch_op:
        batch_op.drop_constraint('fk_google_marathon_tables_user_id_user', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('google_marathon_tables', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_google_marathon_tables_user_id_user', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
