"""empty message

Revision ID: 3b3890df8ee4
Revises: d782c7f2d484
Create Date: 2023-05-26 05:02:18.282865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b3890df8ee4'
down_revision = 'd782c7f2d484'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('name_of_environment_variable_of_marathon_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['marathon_groups.id'], name=op.f('fk_name_of_environment_variable_of_marathon_groups_group_id_marathon_groups')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_name_of_environment_variable_of_marathon_groups'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('name_of_environment_variable_of_marathon_groups')
    # ### end Alembic commands ###
