"""empty message

Revision ID: 3baf050a3624
Revises: 5cb993ca01f7
Create Date: 2023-05-30 07:00:10.207613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3baf050a3624'
down_revision = '5cb993ca01f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments_under_posts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_comments_under_posts_group_id_marathon_groups', type_='foreignkey')
        batch_op.drop_column('group_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments_under_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_comments_under_posts_group_id_marathon_groups', 'marathon_groups', ['group_id'], ['id'])

    # ### end Alembic commands ###
