"""empty message

Revision ID: 5cb993ca01f7
Revises: c6f61582478a
Create Date: 2023-05-30 03:00:56.320483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cb993ca01f7'
down_revision = 'c6f61582478a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ad_media_column_in_the_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('setting_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_ad_media_column_in_the_table_table_id_table_column_settings', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_ad_media_column_in_the_table_setting_id_table_column_settings'), 'table_column_settings', ['setting_id'], ['id'])
        batch_op.drop_column('table_id')

    with op.batch_alter_table('ad_text_column_in_the_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('setting_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_ad_text_column_in_the_table_table_id_table_column_settings', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_ad_text_column_in_the_table_setting_id_table_column_settings'), 'table_column_settings', ['setting_id'], ['id'])
        batch_op.drop_column('table_id')

    with op.batch_alter_table('headings_column_in_the_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('setting_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_headings_column_in_the_table_table_id_table_column_settings', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_headings_column_in_the_table_setting_id_table_column_settings'), 'table_column_settings', ['setting_id'], ['id'])
        batch_op.drop_column('table_id')

    with op.batch_alter_table('initial_word_ad_media_column_in_the_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('column_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_initial_word_ad_media_column_in_the_table_table_id_ad_media_column_in_the_table', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_initial_word_ad_media_column_in_the_table_column_id_ad_media_column_in_the_table'), 'ad_media_column_in_the_table', ['column_id'], ['id'])
        batch_op.drop_column('table_id')

    with op.batch_alter_table('initial_word_ad_text_column_in_the_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('column_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_initial_word_ad_text_column_in_the_table_table_id_ad_text_column_in_the_table', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_initial_word_ad_text_column_in_the_table_column_id_ad_text_column_in_the_table'), 'ad_text_column_in_the_table', ['column_id'], ['id'])
        batch_op.drop_column('table_id')

    with op.batch_alter_table('initial_word_headings_column_in_the_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('column_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_initial_word_headings_column_in_the_table_table_id_headings_column_in_the_table', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_initial_word_headings_column_in_the_table_column_id_headings_column_in_the_table'), 'headings_column_in_the_table', ['column_id'], ['id'])
        batch_op.drop_column('table_id')

    with op.batch_alter_table('initial_word_launch_status_column_in_the_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('column_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_initial_word_launch_status_column_in_the_table_table_id_launch_status_column_in_the_table', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_initial_word_launch_status_column_in_the_table_column_id_launch_status_column_in_the_table'), 'launch_status_column_in_the_table', ['column_id'], ['id'])
        batch_op.drop_column('table_id')

    with op.batch_alter_table('initial_word_request_stop_column_in_the_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('column_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_initial_word_request_stop_column_in_the_table_table_id_request_stop_column_in_the_table', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_initial_word_request_stop_column_in_the_table_column_id_request_stop_column_in_the_table'), 'request_stop_column_in_the_table', ['column_id'], ['id'])
        batch_op.drop_column('table_id')

    with op.batch_alter_table('initial_word_stop_content_column_in_the_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('column_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_initial_word_stop_content_column_in_the_table_table_id_stop_content_column_in_the_table', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_initial_word_stop_content_column_in_the_table_column_id_stop_content_column_in_the_table'), 'stop_content_column_in_the_table', ['column_id'], ['id'])
        batch_op.drop_column('table_id')

    with op.batch_alter_table('initial_word_target_audience_column_in_the_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('column_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_initial_word_target_audience_column_in_the_table_table_id_target_audience_column_in_the_table', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_initial_word_target_audience_column_in_the_table_column_id_target_audience_column_in_the_table'), 'target_audience_column_in_the_table', ['column_id'], ['id'])
        batch_op.drop_column('table_id')

    with op.batch_alter_table('initial_word_tasks_column_in_the_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('column_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_initial_word_tasks_column_in_the_table_table_id_tasks_column_in_the_table', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_initial_word_tasks_column_in_the_table_column_id_tasks_column_in_the_table'), 'tasks_column_in_the_table', ['column_id'], ['id'])
        batch_op.drop_column('table_id')

    with op.batch_alter_table('initial_word_user_group_column_in_the_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('column_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_initial_word_user_group_column_in_the_table_table_id_user_group_column_in_the_table', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_initial_word_user_group_column_in_the_table_column_id_user_group_column_in_the_table'), 'user_group_column_in_the_table', ['column_id'], ['id'])
        batch_op.drop_column('table_id')

    with op.batch_alter_table('initial_word_user_last_name_column_in_the_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('column_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_initial_word_user_last_name_column_in_the_table_table_id_user_last_name_column_in_the_table', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_initial_word_user_last_name_column_in_the_table_column_id_user_last_name_column_in_the_table'), 'user_last_name_column_in_the_table', ['column_id'], ['id'])
        batch_op.drop_column('table_id')

    with op.batch_alter_table('initial_word_user_name_cabinet_column_in_the_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('column_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_initial_word_user_name_cabinet_column_in_the_table_table_id_user_name_cabinet_column_in_the_table', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_initial_word_user_name_cabinet_column_in_the_table_column_id_user_name_cabinet_column_in_the_table'), 'user_name_cabinet_column_in_the_table', ['column_id'], ['id'])
        batch_op.drop_column('table_id')

    with op.batch_alter_table('initial_word_user_name_column_in_the_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('column_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_initial_word_user_name_column_in_the_table_table_id_user_name_column_in_the_table', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_initial_word_user_name_column_in_the_table_column_id_user_name_column_in_the_table'), 'user_name_column_in_the_table', ['column_id'], ['id'])
        batch_op.drop_column('table_id')

    with op.batch_alter_table('initial_word_user_reference_column_in_the_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('column_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_initial_word_user_reference_column_in_the_table_table_id_user_reference_column_in_the_table', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_initial_word_user_reference_column_in_the_table_column_id_user_reference_column_in_the_table'), 'user_reference_column_in_the_table', ['column_id'], ['id'])
        batch_op.drop_column('table_id')

    with op.batch_alter_table('launch_status_column_in_the_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('setting_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_launch_status_column_in_the_table_table_id_table_column_settings', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_launch_status_column_in_the_table_setting_id_table_column_settings'), 'table_column_settings', ['setting_id'], ['id'])
        batch_op.drop_column('table_id')

    with op.batch_alter_table('number_of_tasks_in_the_marathon_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('setting_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_number_of_tasks_in_the_marathon_table_table_id_table_column_settings', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_number_of_tasks_in_the_marathon_table_setting_id_table_column_settings'), 'table_column_settings', ['setting_id'], ['id'])
        batch_op.drop_column('table_id')

    with op.batch_alter_table('request_stop_column_in_the_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('setting_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_request_stop_column_in_the_table_table_id_table_column_settings', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_request_stop_column_in_the_table_setting_id_table_column_settings'), 'table_column_settings', ['setting_id'], ['id'])
        batch_op.drop_column('table_id')

    with op.batch_alter_table('stop_content_column_in_the_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('setting_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_stop_content_column_in_the_table_table_id_table_column_settings', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_stop_content_column_in_the_table_setting_id_table_column_settings'), 'table_column_settings', ['setting_id'], ['id'])
        batch_op.drop_column('table_id')

    with op.batch_alter_table('target_audience_column_in_the_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('setting_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_target_audience_column_in_the_table_table_id_table_column_settings', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_target_audience_column_in_the_table_setting_id_table_column_settings'), 'table_column_settings', ['setting_id'], ['id'])
        batch_op.drop_column('table_id')

    with op.batch_alter_table('tasks_column_in_the_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('setting_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_tasks_column_in_the_table_table_id_table_column_settings', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_tasks_column_in_the_table_setting_id_table_column_settings'), 'table_column_settings', ['setting_id'], ['id'])
        batch_op.drop_column('table_id')

    with op.batch_alter_table('user_group_column_in_the_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('setting_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_user_group_column_in_the_table_table_id_table_column_settings', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_user_group_column_in_the_table_setting_id_table_column_settings'), 'table_column_settings', ['setting_id'], ['id'])
        batch_op.drop_column('table_id')

    with op.batch_alter_table('user_last_name_column_in_the_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('setting_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_user_last_name_column_in_the_table_table_id_table_column_settings', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_user_last_name_column_in_the_table_setting_id_table_column_settings'), 'table_column_settings', ['setting_id'], ['id'])
        batch_op.drop_column('table_id')

    with op.batch_alter_table('user_name_cabinet_column_in_the_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('setting_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_user_name_cabinet_column_in_the_table_table_id_table_column_settings', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_user_name_cabinet_column_in_the_table_setting_id_table_column_settings'), 'table_column_settings', ['setting_id'], ['id'])
        batch_op.drop_column('table_id')

    with op.batch_alter_table('user_name_column_in_the_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('setting_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_user_name_column_in_the_table_table_id_table_column_settings', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_user_name_column_in_the_table_setting_id_table_column_settings'), 'table_column_settings', ['setting_id'], ['id'])
        batch_op.drop_column('table_id')

    with op.batch_alter_table('user_reference_column_in_the_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('setting_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_user_reference_column_in_the_table_table_id_table_column_settings', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_user_reference_column_in_the_table_setting_id_table_column_settings'), 'table_column_settings', ['setting_id'], ['id'])
        batch_op.drop_column('table_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_reference_column_in_the_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('table_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_user_reference_column_in_the_table_setting_id_table_column_settings'), type_='foreignkey')
        batch_op.create_foreign_key('fk_user_reference_column_in_the_table_table_id_table_column_settings', 'table_column_settings', ['table_id'], ['id'])
        batch_op.drop_column('setting_id')

    with op.batch_alter_table('user_name_column_in_the_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('table_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_user_name_column_in_the_table_setting_id_table_column_settings'), type_='foreignkey')
        batch_op.create_foreign_key('fk_user_name_column_in_the_table_table_id_table_column_settings', 'table_column_settings', ['table_id'], ['id'])
        batch_op.drop_column('setting_id')

    with op.batch_alter_table('user_name_cabinet_column_in_the_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('table_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_user_name_cabinet_column_in_the_table_setting_id_table_column_settings'), type_='foreignkey')
        batch_op.create_foreign_key('fk_user_name_cabinet_column_in_the_table_table_id_table_column_settings', 'table_column_settings', ['table_id'], ['id'])
        batch_op.drop_column('setting_id')

    with op.batch_alter_table('user_last_name_column_in_the_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('table_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_user_last_name_column_in_the_table_setting_id_table_column_settings'), type_='foreignkey')
        batch_op.create_foreign_key('fk_user_last_name_column_in_the_table_table_id_table_column_settings', 'table_column_settings', ['table_id'], ['id'])
        batch_op.drop_column('setting_id')

    with op.batch_alter_table('user_group_column_in_the_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('table_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_user_group_column_in_the_table_setting_id_table_column_settings'), type_='foreignkey')
        batch_op.create_foreign_key('fk_user_group_column_in_the_table_table_id_table_column_settings', 'table_column_settings', ['table_id'], ['id'])
        batch_op.drop_column('setting_id')

    with op.batch_alter_table('tasks_column_in_the_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('table_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_tasks_column_in_the_table_setting_id_table_column_settings'), type_='foreignkey')
        batch_op.create_foreign_key('fk_tasks_column_in_the_table_table_id_table_column_settings', 'table_column_settings', ['table_id'], ['id'])
        batch_op.drop_column('setting_id')

    with op.batch_alter_table('target_audience_column_in_the_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('table_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_target_audience_column_in_the_table_setting_id_table_column_settings'), type_='foreignkey')
        batch_op.create_foreign_key('fk_target_audience_column_in_the_table_table_id_table_column_settings', 'table_column_settings', ['table_id'], ['id'])
        batch_op.drop_column('setting_id')

    with op.batch_alter_table('stop_content_column_in_the_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('table_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_stop_content_column_in_the_table_setting_id_table_column_settings'), type_='foreignkey')
        batch_op.create_foreign_key('fk_stop_content_column_in_the_table_table_id_table_column_settings', 'table_column_settings', ['table_id'], ['id'])
        batch_op.drop_column('setting_id')

    with op.batch_alter_table('request_stop_column_in_the_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('table_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_request_stop_column_in_the_table_setting_id_table_column_settings'), type_='foreignkey')
        batch_op.create_foreign_key('fk_request_stop_column_in_the_table_table_id_table_column_settings', 'table_column_settings', ['table_id'], ['id'])
        batch_op.drop_column('setting_id')

    with op.batch_alter_table('number_of_tasks_in_the_marathon_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('table_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_number_of_tasks_in_the_marathon_table_setting_id_table_column_settings'), type_='foreignkey')
        batch_op.create_foreign_key('fk_number_of_tasks_in_the_marathon_table_table_id_table_column_settings', 'table_column_settings', ['table_id'], ['id'])
        batch_op.drop_column('setting_id')

    with op.batch_alter_table('launch_status_column_in_the_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('table_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_launch_status_column_in_the_table_setting_id_table_column_settings'), type_='foreignkey')
        batch_op.create_foreign_key('fk_launch_status_column_in_the_table_table_id_table_column_settings', 'table_column_settings', ['table_id'], ['id'])
        batch_op.drop_column('setting_id')

    with op.batch_alter_table('initial_word_user_reference_column_in_the_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('table_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_initial_word_user_reference_column_in_the_table_column_id_user_reference_column_in_the_table'), type_='foreignkey')
        batch_op.create_foreign_key('fk_initial_word_user_reference_column_in_the_table_table_id_user_reference_column_in_the_table', 'user_reference_column_in_the_table', ['table_id'], ['id'])
        batch_op.drop_column('column_id')

    with op.batch_alter_table('initial_word_user_name_column_in_the_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('table_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_initial_word_user_name_column_in_the_table_column_id_user_name_column_in_the_table'), type_='foreignkey')
        batch_op.create_foreign_key('fk_initial_word_user_name_column_in_the_table_table_id_user_name_column_in_the_table', 'user_name_column_in_the_table', ['table_id'], ['id'])
        batch_op.drop_column('column_id')

    with op.batch_alter_table('initial_word_user_name_cabinet_column_in_the_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('table_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_initial_word_user_name_cabinet_column_in_the_table_column_id_user_name_cabinet_column_in_the_table'), type_='foreignkey')
        batch_op.create_foreign_key('fk_initial_word_user_name_cabinet_column_in_the_table_table_id_user_name_cabinet_column_in_the_table', 'user_name_cabinet_column_in_the_table', ['table_id'], ['id'])
        batch_op.drop_column('column_id')

    with op.batch_alter_table('initial_word_user_last_name_column_in_the_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('table_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_initial_word_user_last_name_column_in_the_table_column_id_user_last_name_column_in_the_table'), type_='foreignkey')
        batch_op.create_foreign_key('fk_initial_word_user_last_name_column_in_the_table_table_id_user_last_name_column_in_the_table', 'user_last_name_column_in_the_table', ['table_id'], ['id'])
        batch_op.drop_column('column_id')

    with op.batch_alter_table('initial_word_user_group_column_in_the_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('table_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_initial_word_user_group_column_in_the_table_column_id_user_group_column_in_the_table'), type_='foreignkey')
        batch_op.create_foreign_key('fk_initial_word_user_group_column_in_the_table_table_id_user_group_column_in_the_table', 'user_group_column_in_the_table', ['table_id'], ['id'])
        batch_op.drop_column('column_id')

    with op.batch_alter_table('initial_word_tasks_column_in_the_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('table_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_initial_word_tasks_column_in_the_table_column_id_tasks_column_in_the_table'), type_='foreignkey')
        batch_op.create_foreign_key('fk_initial_word_tasks_column_in_the_table_table_id_tasks_column_in_the_table', 'tasks_column_in_the_table', ['table_id'], ['id'])
        batch_op.drop_column('column_id')

    with op.batch_alter_table('initial_word_target_audience_column_in_the_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('table_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_initial_word_target_audience_column_in_the_table_column_id_target_audience_column_in_the_table'), type_='foreignkey')
        batch_op.create_foreign_key('fk_initial_word_target_audience_column_in_the_table_table_id_target_audience_column_in_the_table', 'target_audience_column_in_the_table', ['table_id'], ['id'])
        batch_op.drop_column('column_id')

    with op.batch_alter_table('initial_word_stop_content_column_in_the_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('table_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_initial_word_stop_content_column_in_the_table_column_id_stop_content_column_in_the_table'), type_='foreignkey')
        batch_op.create_foreign_key('fk_initial_word_stop_content_column_in_the_table_table_id_stop_content_column_in_the_table', 'stop_content_column_in_the_table', ['table_id'], ['id'])
        batch_op.drop_column('column_id')

    with op.batch_alter_table('initial_word_request_stop_column_in_the_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('table_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_initial_word_request_stop_column_in_the_table_column_id_request_stop_column_in_the_table'), type_='foreignkey')
        batch_op.create_foreign_key('fk_initial_word_request_stop_column_in_the_table_table_id_request_stop_column_in_the_table', 'request_stop_column_in_the_table', ['table_id'], ['id'])
        batch_op.drop_column('column_id')

    with op.batch_alter_table('initial_word_launch_status_column_in_the_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('table_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_initial_word_launch_status_column_in_the_table_column_id_launch_status_column_in_the_table'), type_='foreignkey')
        batch_op.create_foreign_key('fk_initial_word_launch_status_column_in_the_table_table_id_launch_status_column_in_the_table', 'launch_status_column_in_the_table', ['table_id'], ['id'])
        batch_op.drop_column('column_id')

    with op.batch_alter_table('initial_word_headings_column_in_the_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('table_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_initial_word_headings_column_in_the_table_column_id_headings_column_in_the_table'), type_='foreignkey')
        batch_op.create_foreign_key('fk_initial_word_headings_column_in_the_table_table_id_headings_column_in_the_table', 'headings_column_in_the_table', ['table_id'], ['id'])
        batch_op.drop_column('column_id')

    with op.batch_alter_table('initial_word_ad_text_column_in_the_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('table_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_initial_word_ad_text_column_in_the_table_column_id_ad_text_column_in_the_table'), type_='foreignkey')
        batch_op.create_foreign_key('fk_initial_word_ad_text_column_in_the_table_table_id_ad_text_column_in_the_table', 'ad_text_column_in_the_table', ['table_id'], ['id'])
        batch_op.drop_column('column_id')

    with op.batch_alter_table('initial_word_ad_media_column_in_the_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('table_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_initial_word_ad_media_column_in_the_table_column_id_ad_media_column_in_the_table'), type_='foreignkey')
        batch_op.create_foreign_key('fk_initial_word_ad_media_column_in_the_table_table_id_ad_media_column_in_the_table', 'ad_media_column_in_the_table', ['table_id'], ['id'])
        batch_op.drop_column('column_id')

    with op.batch_alter_table('headings_column_in_the_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('table_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_headings_column_in_the_table_setting_id_table_column_settings'), type_='foreignkey')
        batch_op.create_foreign_key('fk_headings_column_in_the_table_table_id_table_column_settings', 'table_column_settings', ['table_id'], ['id'])
        batch_op.drop_column('setting_id')

    with op.batch_alter_table('ad_text_column_in_the_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('table_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_ad_text_column_in_the_table_setting_id_table_column_settings'), type_='foreignkey')
        batch_op.create_foreign_key('fk_ad_text_column_in_the_table_table_id_table_column_settings', 'table_column_settings', ['table_id'], ['id'])
        batch_op.drop_column('setting_id')

    with op.batch_alter_table('ad_media_column_in_the_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('table_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_ad_media_column_in_the_table_setting_id_table_column_settings'), type_='foreignkey')
        batch_op.create_foreign_key('fk_ad_media_column_in_the_table_table_id_table_column_settings', 'table_column_settings', ['table_id'], ['id'])
        batch_op.drop_column('setting_id')

    # ### end Alembic commands ###
