"""empty message

Revision ID: 79a3e1a7361e
Revises: f205a8de49f6
Create Date: 2023-07-14 03:18:57.081463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79a3e1a7361e'
down_revision = 'f205a8de49f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apscheduler_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jobs_name', sa.String(length=128), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=191),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_index('ix_apscheduler_jobs_next_run_time')
        batch_op.drop_column('job_state')
        batch_op.drop_column('next_run_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apscheduler_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('next_run_time', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('job_state', sa.BLOB(), nullable=False))
        batch_op.create_index('ix_apscheduler_jobs_next_run_time', ['next_run_time'], unique=False)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=191),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_column('jobs_name')

    # ### end Alembic commands ###
