"""empty message

Revision ID: 7f0109a3f623
Revises: c71e2a57b763
Create Date: 2023-07-21 07:13:45.636437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f0109a3f623'
down_revision = 'c71e2a57b763'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('apscheduler_jobs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('job_state', sa.VARCHAR(length=128), nullable=True),
    sa.Column('next_run_time', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
