"""empty message

Revision ID: 82aa172f493e
Revises: 7f0109a3f623
Create Date: 2023-07-21 07:26:53.886761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82aa172f493e'
down_revision = '7f0109a3f623'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apscheduler_jobs', schema=None) as batch_op:
        batch_op.alter_column('job_state',
               existing_type=sa.BLOB(),
               type_=sa.Float(),
               nullable=True)
        batch_op.alter_column('next_run_time',
               existing_type=sa.FLOAT(),
               type_=sa.LargeBinary(),
               existing_nullable=True)
        batch_op.drop_index('ix_apscheduler_jobs_next_run_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apscheduler_jobs', schema=None) as batch_op:
        batch_op.create_index('ix_apscheduler_jobs_next_run_time', ['next_run_time'], unique=False)
        batch_op.alter_column('next_run_time',
               existing_type=sa.LargeBinary(),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('job_state',
               existing_type=sa.Float(),
               type_=sa.BLOB(),
               nullable=False)

    # ### end Alembic commands ###
