"""empty message

Revision ID: 8c992a21df27
Revises: 0095c75abdbc
Create Date: 2023-06-30 04:48:56.795160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c992a21df27'
down_revision = '0095c75abdbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marathon_group_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['marathon_groups.id'], name=op.f('fk_marathon_group_settings_group_id_marathon_groups')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_marathon_group_settings'))
    )
    op.create_table('name_of_the_marathon_group_table_sheet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('setting_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['setting_id'], ['marathon_group_settings.id'], name=op.f('fk_name_of_the_marathon_group_table_sheet_setting_id_marathon_group_settings')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_name_of_the_marathon_group_table_sheet'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('name_of_the_marathon_group_table_sheet')
    op.drop_table('marathon_group_settings')
    # ### end Alembic commands ###
