"""google tables have been added and a link has been created between the marathon group and the table

Revision ID: 8d399b7c4423
Revises: 3741118028e3
Create Date: 2023-05-28 06:57:00.115143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d399b7c4423'
down_revision = '3741118028e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('google_marathon_tables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link_to_the_table', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('time_of_addition', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_google_marathon_tables_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_google_marathon_tables'))
    )
    with op.batch_alter_table('google_marathon_tables', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_google_marathon_tables_link_to_the_table'), ['link_to_the_table'], unique=True)

    op.create_table('tables_linked_to_marathon_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['marathon_groups.id'], name=op.f('fk_tables_linked_to_marathon_groups_group_id_marathon_groups')),
    sa.ForeignKeyConstraint(['table_id'], ['google_marathon_tables.id'], name=op.f('fk_tables_linked_to_marathon_groups_table_id_google_marathon_tables')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tables_linked_to_marathon_groups'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tables_linked_to_marathon_groups')
    with op.batch_alter_table('google_marathon_tables', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_google_marathon_tables_link_to_the_table'))

    op.drop_table('google_marathon_tables')
    # ### end Alembic commands ###
