"""empty message

Revision ID: 928c332731c6
Revises: 3ad8f6b6c4ee
Create Date: 2023-05-28 07:26:01.733926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '928c332731c6'
down_revision = '3ad8f6b6c4ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('google_marathon_tables', schema=None) as batch_op:
        batch_op.alter_column('link_to_the_table',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=512),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('google_marathon_tables', schema=None) as batch_op:
        batch_op.alter_column('link_to_the_table',
               existing_type=sa.String(length=512),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
