"""empty message

Revision ID: c6f61582478a
Revises: 116b0b9852a0
Create Date: 2023-05-30 02:09:23.640419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6f61582478a'
down_revision = '116b0b9852a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks_column_in_the_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('availability', sa.Boolean(), nullable=True),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['table_column_settings.id'], name=op.f('fk_tasks_column_in_the_table_table_id_table_column_settings')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks_column_in_the_table'))
    )
    op.create_table('initial_word_tasks_column_in_the_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=128), nullable=True),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['tasks_column_in_the_table.id'], name=op.f('fk_initial_word_tasks_column_in_the_table_table_id_tasks_column_in_the_table')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_initial_word_tasks_column_in_the_table'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('initial_word_tasks_column_in_the_table')
    op.drop_table('tasks_column_in_the_table')
    # ### end Alembic commands ###
