"""empty message

Revision ID: c71e2a57b763
Revises: 216a322b23c4
Create Date: 2023-07-14 03:30:05.649525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c71e2a57b763'
down_revision = '216a322b23c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apscheduler_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_state', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('next_run_time', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apscheduler_jobs', schema=None) as batch_op:
        batch_op.drop_column('next_run_time')
        batch_op.drop_column('job_state')

    # ### end Alembic commands ###
