"""empty message

Revision ID: ca89af460488
Revises: 928c332731c6
Create Date: 2023-05-29 07:00:20.825606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca89af460488'
down_revision = '928c332731c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ad_media_column_in_the_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('availability', sa.Boolean(), nullable=True),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['google_marathon_tables.id'], name=op.f('fk_ad_media_column_in_the_table_table_id_google_marathon_tables')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ad_media_column_in_the_table'))
    )
    op.create_table('ad_text_column_in_the_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('availability', sa.Boolean(), nullable=True),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['google_marathon_tables.id'], name=op.f('fk_ad_text_column_in_the_table_table_id_google_marathon_tables')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ad_text_column_in_the_table'))
    )
    op.create_table('headings_column_in_the_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('availability', sa.Boolean(), nullable=True),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['google_marathon_tables.id'], name=op.f('fk_headings_column_in_the_table_table_id_google_marathon_tables')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_headings_column_in_the_table'))
    )
    op.create_table('launch_status_column_in_the_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('availability', sa.Boolean(), nullable=True),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['google_marathon_tables.id'], name=op.f('fk_launch_status_column_in_the_table_table_id_google_marathon_tables')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_launch_status_column_in_the_table'))
    )
    op.create_table('number_of_tasks_in_the_marathon_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number_of_tasks', sa.Integer(), nullable=True),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['google_marathon_tables.id'], name=op.f('fk_number_of_tasks_in_the_marathon_table_table_id_google_marathon_tables')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_number_of_tasks_in_the_marathon_table'))
    )
    op.create_table('posts_in_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['marathon_groups.id'], name=op.f('fk_posts_in_groups_group_id_marathon_groups')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_posts_in_groups'))
    )
    op.create_table('request_stop_column_in_the_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('availability', sa.Boolean(), nullable=True),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['google_marathon_tables.id'], name=op.f('fk_request_stop_column_in_the_table_table_id_google_marathon_tables')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_request_stop_column_in_the_table'))
    )
    op.create_table('stop_content_column_in_the_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('availability', sa.Boolean(), nullable=True),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['google_marathon_tables.id'], name=op.f('fk_stop_content_column_in_the_table_table_id_google_marathon_tables')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stop_content_column_in_the_table'))
    )
    op.create_table('table_column_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['google_marathon_tables.id'], name=op.f('fk_table_column_settings_table_id_google_marathon_tables')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_table_column_settings'))
    )
    op.create_table('target_audience_column_in_the_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('availability', sa.Boolean(), nullable=True),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['google_marathon_tables.id'], name=op.f('fk_target_audience_column_in_the_table_table_id_google_marathon_tables')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_target_audience_column_in_the_table'))
    )
    op.create_table('user_group_column_in_the_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('availability', sa.Boolean(), nullable=True),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['google_marathon_tables.id'], name=op.f('fk_user_group_column_in_the_table_table_id_google_marathon_tables')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_group_column_in_the_table'))
    )
    op.create_table('user_last_name_column_in_the_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('availability', sa.Boolean(), nullable=True),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['google_marathon_tables.id'], name=op.f('fk_user_last_name_column_in_the_table_table_id_google_marathon_tables')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_last_name_column_in_the_table'))
    )
    op.create_table('user_name_cabinet_column_in_the_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('availability', sa.Boolean(), nullable=True),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['google_marathon_tables.id'], name=op.f('fk_user_name_cabinet_column_in_the_table_table_id_google_marathon_tables')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_name_cabinet_column_in_the_table'))
    )
    op.create_table('user_name_column_in_the_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('availability', sa.Boolean(), nullable=True),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['google_marathon_tables.id'], name=op.f('fk_user_name_column_in_the_table_table_id_google_marathon_tables')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_name_column_in_the_table'))
    )
    op.create_table('user_reference_column_in_the_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('availability', sa.Boolean(), nullable=True),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['google_marathon_tables.id'], name=op.f('fk_user_reference_column_in_the_table_table_id_google_marathon_tables')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_reference_column_in_the_table'))
    )
    op.create_table('comments_under_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['marathon_groups.id'], name=op.f('fk_comments_under_posts_group_id_marathon_groups')),
    sa.ForeignKeyConstraint(['post_id'], ['posts_in_groups.id'], name=op.f('fk_comments_under_posts_post_id_posts_in_groups')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comments_under_posts'))
    )
    op.create_table('initial_word_ad_media_column_in_the_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=128), nullable=True),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['ad_media_column_in_the_table.id'], name=op.f('fk_initial_word_ad_media_column_in_the_table_table_id_ad_media_column_in_the_table')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_initial_word_ad_media_column_in_the_table'))
    )
    op.create_table('initial_word_ad_text_column_in_the_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=128), nullable=True),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['ad_text_column_in_the_table.id'], name=op.f('fk_initial_word_ad_text_column_in_the_table_table_id_ad_text_column_in_the_table')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_initial_word_ad_text_column_in_the_table'))
    )
    op.create_table('initial_word_headings_column_in_the_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=128), nullable=True),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['headings_column_in_the_table.id'], name=op.f('fk_initial_word_headings_column_in_the_table_table_id_headings_column_in_the_table')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_initial_word_headings_column_in_the_table'))
    )
    op.create_table('initial_word_launch_status_column_in_the_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=128), nullable=True),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['launch_status_column_in_the_table.id'], name=op.f('fk_initial_word_launch_status_column_in_the_table_table_id_launch_status_column_in_the_table')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_initial_word_launch_status_column_in_the_table'))
    )
    op.create_table('initial_word_request_stop_column_in_the_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=128), nullable=True),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['request_stop_column_in_the_table.id'], name=op.f('fk_initial_word_request_stop_column_in_the_table_table_id_request_stop_column_in_the_table')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_initial_word_request_stop_column_in_the_table'))
    )
    op.create_table('initial_word_stop_content_column_in_the_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=128), nullable=True),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['stop_content_column_in_the_table.id'], name=op.f('fk_initial_word_stop_content_column_in_the_table_table_id_stop_content_column_in_the_table')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_initial_word_stop_content_column_in_the_table'))
    )
    op.create_table('initial_word_target_audience_column_in_the_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=128), nullable=True),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['target_audience_column_in_the_table.id'], name=op.f('fk_initial_word_target_audience_column_in_the_table_table_id_target_audience_column_in_the_table')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_initial_word_target_audience_column_in_the_table'))
    )
    op.create_table('initial_word_user_group_column_in_the_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=128), nullable=True),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['user_group_column_in_the_table.id'], name=op.f('fk_initial_word_user_group_column_in_the_table_table_id_user_group_column_in_the_table')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_initial_word_user_group_column_in_the_table'))
    )
    op.create_table('initial_word_user_last_name_column_in_the_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=128), nullable=True),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['user_last_name_column_in_the_table.id'], name=op.f('fk_initial_word_user_last_name_column_in_the_table_table_id_user_last_name_column_in_the_table')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_initial_word_user_last_name_column_in_the_table'))
    )
    op.create_table('initial_word_user_name_cabinet_column_in_the_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=128), nullable=True),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['user_name_cabinet_column_in_the_table.id'], name=op.f('fk_initial_word_user_name_cabinet_column_in_the_table_table_id_user_name_cabinet_column_in_the_table')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_initial_word_user_name_cabinet_column_in_the_table'))
    )
    op.create_table('initial_word_user_name_column_in_the_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=128), nullable=True),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['user_name_column_in_the_table.id'], name=op.f('fk_initial_word_user_name_column_in_the_table_table_id_user_name_column_in_the_table')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_initial_word_user_name_column_in_the_table'))
    )
    op.create_table('initial_word_user_reference_column_in_the_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=128), nullable=True),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['user_reference_column_in_the_table.id'], name=op.f('fk_initial_word_user_reference_column_in_the_table_table_id_user_reference_column_in_the_table')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_initial_word_user_reference_column_in_the_table'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('initial_word_user_reference_column_in_the_table')
    op.drop_table('initial_word_user_name_column_in_the_table')
    op.drop_table('initial_word_user_name_cabinet_column_in_the_table')
    op.drop_table('initial_word_user_last_name_column_in_the_table')
    op.drop_table('initial_word_user_group_column_in_the_table')
    op.drop_table('initial_word_target_audience_column_in_the_table')
    op.drop_table('initial_word_stop_content_column_in_the_table')
    op.drop_table('initial_word_request_stop_column_in_the_table')
    op.drop_table('initial_word_launch_status_column_in_the_table')
    op.drop_table('initial_word_headings_column_in_the_table')
    op.drop_table('initial_word_ad_text_column_in_the_table')
    op.drop_table('initial_word_ad_media_column_in_the_table')
    op.drop_table('comments_under_posts')
    op.drop_table('user_reference_column_in_the_table')
    op.drop_table('user_name_column_in_the_table')
    op.drop_table('user_name_cabinet_column_in_the_table')
    op.drop_table('user_last_name_column_in_the_table')
    op.drop_table('user_group_column_in_the_table')
    op.drop_table('target_audience_column_in_the_table')
    op.drop_table('table_column_settings')
    op.drop_table('stop_content_column_in_the_table')
    op.drop_table('request_stop_column_in_the_table')
    op.drop_table('posts_in_groups')
    op.drop_table('number_of_tasks_in_the_marathon_table')
    op.drop_table('launch_status_column_in_the_table')
    op.drop_table('headings_column_in_the_table')
    op.drop_table('ad_text_column_in_the_table')
    op.drop_table('ad_media_column_in_the_table')
    # ### end Alembic commands ###
