"""empty message

Revision ID: e128f44b30a7
Revises: 79a3e1a7361e
Create Date: 2023-07-14 03:22:10.786511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e128f44b30a7'
down_revision = '79a3e1a7361e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apscheduler_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_state', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('next_run_time', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apscheduler_jobs', schema=None) as batch_op:
        batch_op.drop_column('next_run_time')
        batch_op.drop_column('job_state')

    # ### end Alembic commands ###
