"""empty message

Revision ID: f205a8de49f6
Revises: 268ba756a89a
Create Date: 2023-07-12 13:24:22.458295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f205a8de49f6'
down_revision = '268ba756a89a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_server_callback_api_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=128), nullable=True),
    sa.Column('title', sa.String(length=14), nullable=True),
    sa.Column('secret_key', sa.String(length=50), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['marathon_groups.id'], name=op.f('fk_group_server_callback_api_data_group_id_marathon_groups')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_group_server_callback_api_data'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group_server_callback_api_data')
    # ### end Alembic commands ###
