"""empty message

Revision ID: f57b08ce6ffa
Revises: 3b3890df8ee4
Create Date: 2023-05-26 05:21:13.952937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f57b08ce6ffa'
down_revision = '3b3890df8ee4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_who_have_add_marathon_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('time_of_addition', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['marathon_groups.id'], name=op.f('fk_users_who_have_add_marathon_groups_group_id_marathon_groups')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_users_who_have_add_marathon_groups_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users_who_have_add_marathon_groups'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_who_have_add_marathon_groups')
    # ### end Alembic commands ###
