"""empty message

Revision ID: fae8a34e5a14
Revises: ca89af460488
Create Date: 2023-05-29 07:04:24.218064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fae8a34e5a14'
down_revision = 'ca89af460488'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ad_media_column_in_the_table', schema=None) as batch_op:
        batch_op.drop_constraint('fk_ad_media_column_in_the_table_table_id_google_marathon_tables', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_ad_media_column_in_the_table_table_id_table_column_settings'), 'table_column_settings', ['table_id'], ['id'])

    with op.batch_alter_table('ad_text_column_in_the_table', schema=None) as batch_op:
        batch_op.drop_constraint('fk_ad_text_column_in_the_table_table_id_google_marathon_tables', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_ad_text_column_in_the_table_table_id_table_column_settings'), 'table_column_settings', ['table_id'], ['id'])

    with op.batch_alter_table('headings_column_in_the_table', schema=None) as batch_op:
        batch_op.drop_constraint('fk_headings_column_in_the_table_table_id_google_marathon_tables', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_headings_column_in_the_table_table_id_table_column_settings'), 'table_column_settings', ['table_id'], ['id'])

    with op.batch_alter_table('launch_status_column_in_the_table', schema=None) as batch_op:
        batch_op.drop_constraint('fk_launch_status_column_in_the_table_table_id_google_marathon_tables', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_launch_status_column_in_the_table_table_id_table_column_settings'), 'table_column_settings', ['table_id'], ['id'])

    with op.batch_alter_table('request_stop_column_in_the_table', schema=None) as batch_op:
        batch_op.drop_constraint('fk_request_stop_column_in_the_table_table_id_google_marathon_tables', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_request_stop_column_in_the_table_table_id_table_column_settings'), 'table_column_settings', ['table_id'], ['id'])

    with op.batch_alter_table('stop_content_column_in_the_table', schema=None) as batch_op:
        batch_op.drop_constraint('fk_stop_content_column_in_the_table_table_id_google_marathon_tables', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_stop_content_column_in_the_table_table_id_table_column_settings'), 'table_column_settings', ['table_id'], ['id'])

    with op.batch_alter_table('target_audience_column_in_the_table', schema=None) as batch_op:
        batch_op.drop_constraint('fk_target_audience_column_in_the_table_table_id_google_marathon_tables', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_target_audience_column_in_the_table_table_id_table_column_settings'), 'table_column_settings', ['table_id'], ['id'])

    with op.batch_alter_table('user_group_column_in_the_table', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_group_column_in_the_table_table_id_google_marathon_tables', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_user_group_column_in_the_table_table_id_table_column_settings'), 'table_column_settings', ['table_id'], ['id'])

    with op.batch_alter_table('user_last_name_column_in_the_table', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_last_name_column_in_the_table_table_id_google_marathon_tables', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_user_last_name_column_in_the_table_table_id_table_column_settings'), 'table_column_settings', ['table_id'], ['id'])

    with op.batch_alter_table('user_name_cabinet_column_in_the_table', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_name_cabinet_column_in_the_table_table_id_google_marathon_tables', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_user_name_cabinet_column_in_the_table_table_id_table_column_settings'), 'table_column_settings', ['table_id'], ['id'])

    with op.batch_alter_table('user_name_column_in_the_table', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_name_column_in_the_table_table_id_google_marathon_tables', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_user_name_column_in_the_table_table_id_table_column_settings'), 'table_column_settings', ['table_id'], ['id'])

    with op.batch_alter_table('user_reference_column_in_the_table', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_reference_column_in_the_table_table_id_google_marathon_tables', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_user_reference_column_in_the_table_table_id_table_column_settings'), 'table_column_settings', ['table_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_reference_column_in_the_table', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_reference_column_in_the_table_table_id_table_column_settings'), type_='foreignkey')
        batch_op.create_foreign_key('fk_user_reference_column_in_the_table_table_id_google_marathon_tables', 'google_marathon_tables', ['table_id'], ['id'])

    with op.batch_alter_table('user_name_column_in_the_table', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_name_column_in_the_table_table_id_table_column_settings'), type_='foreignkey')
        batch_op.create_foreign_key('fk_user_name_column_in_the_table_table_id_google_marathon_tables', 'google_marathon_tables', ['table_id'], ['id'])

    with op.batch_alter_table('user_name_cabinet_column_in_the_table', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_name_cabinet_column_in_the_table_table_id_table_column_settings'), type_='foreignkey')
        batch_op.create_foreign_key('fk_user_name_cabinet_column_in_the_table_table_id_google_marathon_tables', 'google_marathon_tables', ['table_id'], ['id'])

    with op.batch_alter_table('user_last_name_column_in_the_table', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_last_name_column_in_the_table_table_id_table_column_settings'), type_='foreignkey')
        batch_op.create_foreign_key('fk_user_last_name_column_in_the_table_table_id_google_marathon_tables', 'google_marathon_tables', ['table_id'], ['id'])

    with op.batch_alter_table('user_group_column_in_the_table', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_group_column_in_the_table_table_id_table_column_settings'), type_='foreignkey')
        batch_op.create_foreign_key('fk_user_group_column_in_the_table_table_id_google_marathon_tables', 'google_marathon_tables', ['table_id'], ['id'])

    with op.batch_alter_table('target_audience_column_in_the_table', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_target_audience_column_in_the_table_table_id_table_column_settings'), type_='foreignkey')
        batch_op.create_foreign_key('fk_target_audience_column_in_the_table_table_id_google_marathon_tables', 'google_marathon_tables', ['table_id'], ['id'])

    with op.batch_alter_table('stop_content_column_in_the_table', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_stop_content_column_in_the_table_table_id_table_column_settings'), type_='foreignkey')
        batch_op.create_foreign_key('fk_stop_content_column_in_the_table_table_id_google_marathon_tables', 'google_marathon_tables', ['table_id'], ['id'])

    with op.batch_alter_table('request_stop_column_in_the_table', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_request_stop_column_in_the_table_table_id_table_column_settings'), type_='foreignkey')
        batch_op.create_foreign_key('fk_request_stop_column_in_the_table_table_id_google_marathon_tables', 'google_marathon_tables', ['table_id'], ['id'])

    with op.batch_alter_table('launch_status_column_in_the_table', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_launch_status_column_in_the_table_table_id_table_column_settings'), type_='foreignkey')
        batch_op.create_foreign_key('fk_launch_status_column_in_the_table_table_id_google_marathon_tables', 'google_marathon_tables', ['table_id'], ['id'])

    with op.batch_alter_table('headings_column_in_the_table', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_headings_column_in_the_table_table_id_table_column_settings'), type_='foreignkey')
        batch_op.create_foreign_key('fk_headings_column_in_the_table_table_id_google_marathon_tables', 'google_marathon_tables', ['table_id'], ['id'])

    with op.batch_alter_table('ad_text_column_in_the_table', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_ad_text_column_in_the_table_table_id_table_column_settings'), type_='foreignkey')
        batch_op.create_foreign_key('fk_ad_text_column_in_the_table_table_id_google_marathon_tables', 'google_marathon_tables', ['table_id'], ['id'])

    with op.batch_alter_table('ad_media_column_in_the_table', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_ad_media_column_in_the_table_table_id_table_column_settings'), type_='foreignkey')
        batch_op.create_foreign_key('fk_ad_media_column_in_the_table_table_id_google_marathon_tables', 'google_marathon_tables', ['table_id'], ['id'])

    # ### end Alembic commands ###
